### ISSUE TITLE
Syntax error on braceless if-else statements

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/color-debug#13]
The following code breaks:

```c
#include <ColorDebug.h>

int main(void)
{
    if (0)
        CD_INFO("if\n");
    else
        CD_INFO("else\n");

    return 0;
}
```

Turns out we are misusing all do-whiles: they should encompass the macro from start to end AND lack a trailing semicolon. See:

* https://codereview.stackexchange.com/a/4502
* https://codereview.stackexchange.com/q/1679
* https://kernelnewbies.org/FAQ/DoWhile0 (see last comment for an gcc-oriented alternative solution)

**Comment by PeterBowman** [comment]
Prior to this fix, no semicolon was needed after each instruction containing a CD macro (which I find rather counterintuitive and dangerous), see https://github.com/asrob-uc3m/robotDevastation/commit/962829a45c787435b12e1030e07c277c9cf344f9.

**Comment by jgvictores** [comment]
Oh yes, I agree requiring a semicolon is definitely better!

**Comment by jgvictores** [comment]
Thank you!!!!!
