### ISSUE TITLE
Avoid name clashes in macro definitions

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/color-debug#14]
`RESET`, `GREEN`, `RED`... all of this should be prefixed to not incur in name clashes with macros defined by other components.

https://github.com/roboticslab-uc3m/color-debug/blob/27498865e223a531e63058f05d2a7e041b6382e8/ColorDebug.h#L90-L106

Perhaps `CD_RESET`, `CD_GREEN`, etc.?

**Comment by jgvictores** [comment]
Makes sense... They are usually used internally except for RD as far as I recall... Any idea on b/w compat and/or deprecation message?

**Comment by PeterBowman** [comment]
B/W compat is easy, just `#define RED CD_RED` and so on. Regarding compiler messages, YARP uses its own deprecation macros, which in turn expand to MSC/GCC compiler attributes: [ref](https://github.com/robotology/yarp/tree/bbf4db7c9965dabd7b0f8f42c3d0741c081bdec4/src/libYARP_conf/include/yarp/conf).

However, if we follow that path (preserving old names instead of a global rename), there should be a CMake option such as `CMAKE_NO_DEPRECATED` that would disable B/W and deprecations messages altogether. If name clashes already occur (so far not our case, but maybe someone else's out there), consumers should be able to get rid of old macros regardless of back compat.
