### ISSUE TITLE
Allow users to disable color output via CMake option

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/color-debug#20]
As a follow-up to https://github.com/roboticslab-uc3m/color-debug/issues/5, I noticed that certain colors are not as nicely rendered as on Linux (e.g. yellow warnings look white on PowerShell) and even hard to read (e.g. blue debug messages both on PowerShell and CMD). Perhaps we could add another CMake option in [ColorDebugOptions.cmake](https://github.com/roboticslab-uc3m/color-debug/blob/900824d956fb4ddbfcbda6b633e0c7a493e2aeed/cmake/ColorDebugOptions.cmake) so that users can disable colors altogether. Should it be available to non-Windows users, too?

**Comment by jgvictores** [comment]
Related: #21

> Should it be available to non-Windows users, too?

Yes!

**Comment by jgvictores** [comment]
Maybe support the `NO_COLOR` environment variable as proposed by https://no-color.org/ ?
- Note: software that supports it can be added to the site as specified at https://github.com/jcs/no_color

**Comment by PeterBowman** [comment]
Proposal:

* In CMake code, check for the existence of a `NO_COLOR` env variable.
* Locally, check whether a CMake option (as usual, accessible through `-Dopt` in CLI or ccmake) is available and set: `CD_NO_COLOR`.

`${CD_NO_COLOR}` overrides `$ENV{NO_COLOR}`. If either one is set (default for the former: `FALSE`), log level colors and their corresponding CMake options are disabled. `CD_NO_COLOR` has higher precedence than the env variable.

**Comment by PeterBowman** [comment]
> `${CD_NO_COLOR}` overrides `$ENV{NO_COLOR}`.

Sorry, this should be the other way around: if ´$ENV{NO_COLOR}´ is set, don't even bother presenting a `CD_NO_COLOR` to the user. I'd show a status message during the CMake configuration stage, though.

**Comment by PeterBowman** [comment]
> Sorry, this should be the other way around

No, not really, sorry again:

> 2. How should configuration files and command-line arguments be processed in the presence of $NO_COLOR?
>
>    User-level configuration files and per-instance command-line arguments should override $NO_COLOR. A user should be able to export $NO_COLOR in their shell configuration file as a default, but configure a specific program in its configuration file to specifically enable color.
>
>    This also means that software that can add color but doesn't by default does not need to care about $NO_COLOR, because it will only ever be adding color when instructed to do so (as it should be).

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/color-debug/commit/46748d91ad2baf856f09cbe45a059749a933361a + https://github.com/roboticslab-uc3m/color-debug/commit/2e2a5bf5a202228985612008967fb63ba8be53d8 + https://github.com/jcs/no_color/pull/46.
