### ISSUE TITLE
Rename 'test' occurences to 'example'

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/color-debug#4]
- [x] Rename `test` occurrences to `example`, as they are not technically tests.
- [x] Update figure.

**Comment by PeterBowman** [comment]
Done at 0d4b642 (develop).

**Comment by jgvictores** [comment]
Thanks a lot!
Not reflected by default as you merged to `develop`. Two options here **not mutually exclusive**:
1) Merge to `master`.
2) Set `develop`

Ok to do both?

**Comment by PeterBowman** [comment]
Let me finish another tweak, I'm about to merge it to master. OK to setting develop as default, but why do we need two main branches in this repo? Feels like overkill...

**Comment by jgvictores** [comment]
Are you proposing only `master`?

**Comment by jgvictores** [comment]
PS: I'm ok with setting `develop` as default, not merging, just normal gitflow.

**Comment by PeterBowman** [comment]
> Are you proposing only master?

Yes, but I'm not sure now. There are no contributing guidelines in this repo, so no implied gitflow workflow whatsoever.

**Comment by jgvictores** [comment]
For now simply set `develop` as default.
