### ISSUE TITLE
Think about Windows 10 color console

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/color-debug#5]
From the Official blog: https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

However, note that there have been issues with certain releases such as Windows 10 Anniversary Update [[ref](https://github.com/symfony/symfony/issues/19520)].

**Comment by PeterBowman** [comment]
We'll need to check for availability of the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` macro, check that it's set correctly, and then include this C code in the header (I know, bad practice). Refs:

* https://docs.microsoft.com/en-us/windows/console/setconsolemode#ENABLE_VIRTUAL_TERMINAL_PROCESSING
* https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
* https://bugs.php.net/bug.php?id=72768
* https://cmake.org/cmake/help/v3.0/command/try_compile.html
* https://cmake.org/cmake/help/v3.0/command/try_run.html
* https://cmake.org/cmake/help/v3.0/module/CheckCSourceRuns.html
* https://stackoverflow.com/questions/38772468/setconsolemode-and-enable-virtual-terminal-processing

**Comment by PeterBowman** [comment]
Expanding on my previous comment:

* Command-line color support in Windows 10 is disabled by default.
* For the record, this is how you enable fancy colors:
  ```c
  #include <windows.h>
  
  int main(void) {
    HANDLE hStdout;
    DWORD handleMode;
  
    hStdout = GetStdHandle(STD_OUTPUT_HANDLE);
    GetConsoleMode(hStdout, &handleMode);
    handleMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hStdout, handleMode);
  
    return 0;
  }
* IMO the only way to be sure that such code works is performing system introspection with CMake (e.g. `try_run()` or `check_c_source_runs()`), which implies working with templates (e.g. `ColorDebug.hpp.in`).
* If successful, we would add this code to the final `ColorDebug.hpp` and make it callable (instead of living in a macro), that is, parse and run it everytime this header is transcluded.
* YCM does not cope well with CMake code. This is the dealbreaker as of now.

Sadly, the most realistic solution is to remove font markers altogether, see [asrob-uc3m/robotDevastation/src/libraries/UtilsLib/Macros.hpp](https://github.com/asrob-uc3m/robotDevastation/blob/3a53271db524293e4d523a947064d8d010110947/src/libraries/UtilsLib/Macros.hpp#L24-L42).

**Comment by PeterBowman** [comment]
Colors markers on Windows have been removed at 5d1d073.

**Comment by PeterBowman** [comment]
It's not possible to execute C code before (i.e. outside) `main()` in a portable manner. However, there are some obscure hacks for MSVC, see https://www.codeguru.com/cpp/misc/misc/applicationcontrol/article.php/c6945/Running-Code-Before-and-After-Main.htm (posted in 2004...).

**Comment by jgvictores** [comment]
More obscure tactics:
- https://stackoverflow.com/questions/10897552/call-a-function-before-main

**Comment by PeterBowman** [comment]
Sure, but this would work only on C++.

**Comment by jgvictores** [comment]
Oh, ok. Hadn't thought about that.

**Comment by PeterBowman** [comment]
CMake provides its own utilities for coloured console output, see https://stackoverflow.com/a/36233927. This works even on Windows (CMake 3.10.0, Win10):

```
cmake -E cmake_echo_color --green "Hey, I'm green"
```

**Comment by PeterBowman** [comment]
>     * YCM does not cope well with CMake code. This is the dealbreaker as of now.

Not anymore since we require consuming both YCM and color-debug as hard deps.

By the way, the [googletest framework](https://github.com/google/googletest) also generates color output on Windows 10.

**Comment by PeterBowman** [comment]
Idea: move the code proposed at https://github.com/roboticslab-uc3m/color-debug/issues/5#issuecomment-358716226 into a function and add a boolean guard so that it's executed at most **once** in the entire program flow. For that to succeed, the definition should be placed in a .c file and a library be generated specifically for Windows consumers that support VT+colors.

@jgvictores OK to make this non-header-only on Windows 10? Also, I'm not sure (yet) how to avoid concurrent access from several threads, nor whether this could actually pose a real risk.

**Comment by jgvictores** [comment]
Sounds great!

**Comment by PeterBowman** [comment]
I've noted this down somewhere else: configure Travis CI for Linux & **Windows** builds (https://github.com/roboticslab-uc3m/questions-and-answers/issues/51#issuecomment-434335899).

**Comment by PeterBowman** [comment]
> Idea: move the code proposed at [#5 (comment)](https://github.com/roboticslab-uc3m/color-debug/issues/5#issuecomment-358716226) into a function and add a boolean guard so that it's executed at most **once** in the entire program flow.

I think a local static variable might suit those needs: https://stackoverflow.com/a/8412667.

> Also, I'm not sure (yet) how to avoid concurrent access from several threads, nor whether this could actually pose a real risk.

See https://stackoverflow.com/a/8412661.

**Comment by PeterBowman** [comment]
Although we are specifically focusing Windows 10, let me stress again that we *could* enable color output as far as in Windows 2000 thanks to [ANSICON](https://github.com/adoxa/ansicon). That should not be difficult to accomplish (https://stackoverflow.com/q/29423082), but I lack a pre-Windows 10 machine to test ColorDebug on.

**Comment by jgvictores** [comment]
> I lack a pre-Windows 10 machine to test ColorDebug on.

For the record, I just logged into [UC3M Aula Virtual](https://aulavirtual.uc3m.es) (use username without `@domain` in credentials), selected `Windows EPS`... and got `Windows 7 + MSVS 2005`!
