### ISSUE TITLE
Duplicate target found locally

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/color-debug#8]
Caused by 558e051 (#6). Steps to reproduce this issue:

* (optional?) install YCM (tested: v0.6.0)
* clone and configure color-debug, but **skip installation** (`sudo make install`)
* on a YCM-aware repository (e.g. [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/)), create a `build/` directory and run `cmake .. -DUSE_SYSTEM_COLOR_DEBUG=OFF` from within

Console output:

```
CMake Warning (dev) at /usr/local/share/YCM/modules/FindOrBuildPackage.cmake:232 (message):
  A COLOR_DEBUG target already exists before including BuildCOLOR_DEBUG.
Call Stack (most recent call first):
  CMakeLists.txt:72 (find_or_build_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at /usr/local/share/YCM/modules/YCMEPHelper.cmake:664 (message):
  Failed to add target COLOR_DEBUG.  A target with the same name already
  exists.
Call Stack (most recent call first):
  cmake/BuildCOLOR_DEBUG.cmake:3 (ycm_ep_helper)
  /usr/local/share/YCM/modules/FindOrBuildPackage.cmake:235 (include)
  CMakeLists.txt:72 (find_or_build_package)


CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1173 (message):
  External project "COLOR_DEBUG" has no INSTALL_DIR
Call Stack (most recent call first):
  cmake/BuildCOLOR_DEBUG.cmake:9 (ExternalProject_Get_Property)
  /usr/local/share/YCM/modules/FindOrBuildPackage.cmake:235 (include)
  CMakeLists.txt:72 (find_or_build_package)


-- Configuring incomplete, errors occurred!
```

Explanation: in spite of having disabled `USE_SYSTEM_COLOR_DEBUG`, an internal call to `find_package()` locates the `build/` directory of the locally cloned copy of color-debug and loads its config file. YCM invokes then `include(BuildCOLOR_DEBUG)` (as expected), but a `COLOR_DEBUG` target already exists since `COLOR_DEBUGConfig.cmake` (with the lines introduced in 558e051) creates a conflicting target with the same name.

**Comment by PeterBowman** [comment]
Done locally (CMake export config file + README) and in downstreams (root CMake list file), see previously referenced commits. Some light has been shed at https://github.com/roboticslab-uc3m/color-debug/issues/6#issuecomment-365561873 about what was going on. I wanted to have the `add_library(COLOR_DEBUG UNKNOWN IMPORTED)` hack in one place in order to avoid duplicity, but this is not going to work in the conditions described here.

**Comment by jgvictores** [comment]
Recommendation if we ever bump into this again is clearing `.cmake/COLOR_DEBUG` (should be enough) in case old `color-debug` versions from other projects are being used.
